<?xml version="1.0" encoding="utf-8"?><Database Name="BetterTaskList_Progress" Class="BetterTaskListDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.20.240.11;Initial Catalog=BetterTaskList_Progress;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BetterTaskListConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Users" Member="Users">
    <Type Name="User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_Profile" Member="Profiles" ThisKey="UserId" OtherKey="UserId" Type="Profile" />
    </Type>
  </Table>
  <Table Name="dbo.BetterTaskList_AuditTrail" Member="AuditTrails">
    <Type Name="AuditTrail">
      <Column Name="AuditTrailId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AuditEventType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AuditEventCategory" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AuditEventTimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AuditEventDescription" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AuditEventForeingKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Ticket_AuditTrail" Member="Ticket" ThisKey="AuditEventForeingKey" OtherKey="TicketId" Type="Ticket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BetterTaskList_Activity_Feed" Member="ActivityFeeds">
    <Type Name="ActivityFeed">
      <Column Name="FeedId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FeedActionDescription" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="FeedActionCreatorUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FeedActionTimeStamp" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="FeedActionDetails" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="FeedMoreUrl" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BetterTaskList_Ticket_Comment" Member="TicketComments">
    <Type Name="TicketComment">
      <Column Name="TicketId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TicketCommentId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TicketCommentKarma" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TicketCommentDetails" Type="System.String" DbType="NVarChar(1500) NOT NULL" CanBeNull="false" />
      <Column Name="TicketCommentParentId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TicketCommentTimeStamp" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="TicketCommentSubmitterUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Ticket_TicketComment" Member="Ticket" ThisKey="TicketId" OtherKey="TicketId" Type="Ticket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BetterTaskList_Stream_Comment" Member="StreamComments">
    <Type Name="StreamComment">
      <Column Name="StreamId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="StreamCommentId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StreamCommentDetails" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="StreamCommentParentId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="StreamCommentTimeStamp" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="StreamCommentLikesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StreamCommentSubmitterUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StreamCommentSubmitterFullName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="Stream_StreamComment" Member="Stream" ThisKey="StreamId" OtherKey="StreamId" Type="Stream" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BetterTaskList_CoWorker" Member="CoWorkers">
    <Type Name="CoWorker">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AreFriends" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CoWorkerId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoWorkerUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BetterTaskList_Stream" Member="Streams">
    <Type Name="Stream">
      <Column Name="StreamId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StreamType" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="StreamDetails" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="StreamLikesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StreamTargetUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StreamCreatorUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StreamCommentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StreamCreatorFullName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="StreamCreatedTimeStamp" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="StreamLastUpdatedTimeStamp" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Stream_StreamComment" Member="StreamComments" ThisKey="StreamId" OtherKey="StreamId" Type="StreamComment" />
    </Type>
  </Table>
  <Table Name="dbo.BetterTaskList_Profile" Member="Profiles">
    <Type Name="Profile">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProfileId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="AboutMe" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeZone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PictureName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CellPhoneCarrier" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CellPhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkPhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="User_Profile" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BetterTaskList_Ticket" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="TicketId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TicketTags" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TicketStatus" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TicketPriority" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="TicketSubject" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TicketDueDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="TicketDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TicketCreatedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="TicketLastUpdated" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="TicketCreatorUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TicketResolutionTime" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TicketStartTimeStamp" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="TicketOwnersEmailList" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="TicketFinishTimeStamp" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="TicketResolutionDetails" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TicketResolvedByUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TicketEmailNotificationList" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Association Name="Ticket_AuditTrail" Member="AuditTrails" ThisKey="TicketId" OtherKey="AuditEventForeingKey" Type="AuditTrail" />
      <Association Name="Ticket_TicketComment" Member="TicketComments" ThisKey="TicketId" OtherKey="TicketId" Type="TicketComment" />
    </Type>
  </Table>
</Database>